### ISSUE TITLE
Option for empty lines before and after comment

### ISSUE THREAD

**Issue by tomassebestik** [jamief/vscode-ssh-config-enhanced#2]
Hi @jamief,
cool extension and formatter! 🚀

Would be possible to config number of empty lines after comment line?

When hit `Format document`, this input:
```py
Host *
    # Allow the use of local keys remotely
    ForwardAgent yes
    # Automatically add keys to the SSH agent
    AddKeysToAgent yes
    # Send a keepalive packet every 4 minutes to prevent the connection timing out
    ServerAliveInterval 240

# Office Jump Server
Host bastion
    HostName xxxxxxxx.com
    User tomas
    Port 1234
```

... turns to :
```py
Host *
    # Allow the use of local keys remotely
    ForwardAgent yes
    # Automatically add keys to the SSH agent
    AddKeysToAgent yes
    # Send a keepalive packet every 4 minutes to prevent the connection timing out
    ServerAliveInterval 240

# Office Jump Server
             <------(this empty line added)
Host bastion
    HostName xxxxxxxx.com
    User tomas
    Port 1234
```

That visual is a bit confusing. 

**Would be nice if formatter wouldn't force empty line after the section comment.**

**Comment by jamief** [comment]
Hi @tomassebestik,

Thank you for your suggestion and support for the extension!

The issue you raised regarding the empty lines after comments has been addressed and the new version has been published, let me know if you encounter any further issues!

Thanks!

**Comment by tomassebestik** [comment]
Hi @jamief,
Thanks for super-fast update. It works as expected! ❤️
